id: P009518
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4263
  title: རྗེ་བཙུན་ངག་དབང་སྐལ་ལྡན་རྒྱ་མཚོའི་ལྗགས་རྩོམ་གཅེས་བསྡུས་ནོར་བུའི་ཕྲེང་བ
  author: ''
  volumes:
    18ab539e982b4f6c8fc854b85efa290a:
      image_group_id: I1KG4989
      title: ''
      volume_number: 1
      total_pages: 170
      base_file: v001.txt
